/* eslint-disable import/no-anonymous-default-export */
import React from 'react';

import { Box, Center } from '../Layout/index';
import { Text } from './index';

import {
  AcceptIcon,
  AddIcon,
  AddEventIcon,
  AddFriendIcon,
  AddInIcon,
  AttachIcon,
  BackIcon,
  BulletedListIcon,
  BulletedList2Icon,
  CalculatorIcon,
  CalendarIcon,
  CalendarAgendaIcon,
  CancelIcon,
  ChartIcon,
  CheckListIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleRingIcon,
  ClearNightIcon,
  CommentIcon,
  ContactIcon,
  CopyIcon,
  CutIcon,
  DeleteIcon,
  DownIcon,
  DownloadIcon,
  DragObjectIcon,
  EditIcon,
  EditContactIcon,
  EditEventIcon,
  EmbedIcon,
  ErrorIcon,
  EventIcon,
  EventAcceptedIcon,
  EventDateIcon,
  EventDeclinedIcon,
  EventInfoIcon,
  FabricFolderIcon,
  FabricFolderUploadIcon,
  FabricMovetoFolderIcon,
  FabricNewFolderIcon,
  FabricUserFolderIcon,
  FavoriteStarIcon,
  FavoriteStarFillIcon,
  FlagIcon,
  ForwardIcon,
  ForwardEventIcon,
  GlobalNavButtonIcon,
  GridViewMediumIcon,
  GripperBarHorizontalIcon,
  GripperBarVerticalIcon,
  GripperDotsVerticalIcon,
  GroupIcon,
  HeartIcon,
  HelpIcon,
  HistoryIcon,
  HomeIcon,
  ImportantIcon,
  InfoIcon,
  KeyboardClassicIcon,
  LinkIcon,
  ListIcon,
  LocaleLanguageIcon,
  LockIcon,
  MailIcon,
  MegaphoneIcon,
  MoreIcon,
  MoreVerticalIcon,
  NumberedListIcon,
  OpenFileIcon,
  OrgIcon,
  PageIcon,
  PeopleIcon,
  Photo2Icon,
  PinnedIcon,
  PrintIcon,
  RecentIcon,
  RecurringEventIcon,
  RecycleBinIcon,
  RedoIcon,
  RefreshIcon,
  RemoveEventIcon,
  RenameIcon,
  ReplyIcon,
  ReplyAllIcon,
  ReturnToSessionIcon,
  RevToggleKeyIcon,
  RingerIcon,
  RingerActiveIcon,
  RingerOffIcon,
  RingerRemoveIcon,
  SearchIcon,
  SettingsIcon,
  ShareIcon,
  SortIcon,
  SortDownIcon,
  SortLinesIcon,
  SortLinesAscendingIcon,
  SortUpIcon,
  StackIcon,
  StatusCircleCheckmarkIcon,
  StatusCircleErrorXIcon,
  SunnyIcon,
  SyncIcon,
  TVMonitorIcon,
  TableIcon,
  TagIcon,
  TagGroupIcon,
  TestBeakerIcon,
  TestBeakerSolidIcon,
  TranslateIcon,
  UndoIcon,
  UnlockIcon,
  UpIcon,
  UpdateRestoreIcon,
  UploadIcon,
  UserRemoveIcon,
  WaffleOffice365Icon,
  WarningIcon,
} from './index';

export default {
  title: 'Element/Icon',
  component: AddIcon,
};
export const IconsList = () => (
  <Box display="flex" flexWrap="wrap">
    {[
      AcceptIcon,
      AddIcon,
      AddEventIcon,
      AddFriendIcon,
      AddInIcon,
      AttachIcon,
      BackIcon,
      BulletedListIcon,
      BulletedList2Icon,
      CalculatorIcon,
      CalendarIcon,
      CalendarAgendaIcon,
      CancelIcon,
      ChartIcon,
      CheckListIcon,
      ChevronDownIcon,
      ChevronLeftIcon,
      ChevronRightIcon,
      ChevronUpIcon,
      CircleRingIcon,
      ClearNightIcon,
      CommentIcon,
      ContactIcon,
      CopyIcon,
      CutIcon,
      DeleteIcon,
      DownIcon,
      DownloadIcon,
      DragObjectIcon,
      EditIcon,
      EditContactIcon,
      EditEventIcon,
      EmbedIcon,
      ErrorIcon,
      EventIcon,
      EventAcceptedIcon,
      EventDateIcon,
      EventDeclinedIcon,
      EventInfoIcon,
      FabricFolderIcon,
      FabricFolderUploadIcon,
      FabricMovetoFolderIcon,
      FabricNewFolderIcon,
      FabricUserFolderIcon,
      FavoriteStarIcon,
      FavoriteStarFillIcon,
      FlagIcon,
      ForwardIcon,
      ForwardEventIcon,
      GlobalNavButtonIcon,
      GridViewMediumIcon,
      GripperBarHorizontalIcon,
      GripperBarVerticalIcon,
      GripperDotsVerticalIcon,
      GroupIcon,
      HeartIcon,
      HelpIcon,
      HistoryIcon,
      HomeIcon,
      ImportantIcon,
      InfoIcon,
      KeyboardClassicIcon,
      LinkIcon,
      ListIcon,
      LocaleLanguageIcon,
      LockIcon,
      MailIcon,
      MegaphoneIcon,
      MoreIcon,
      MoreVerticalIcon,
      NumberedListIcon,
      OpenFileIcon,
      OrgIcon,
      PageIcon,
      PeopleIcon,
      Photo2Icon,
      PinnedIcon,
      PrintIcon,
      RecentIcon,
      RecurringEventIcon,
      RecycleBinIcon,
      RedoIcon,
      RefreshIcon,
      RemoveEventIcon,
      RenameIcon,
      ReplyIcon,
      ReplyAllIcon,
      ReturnToSessionIcon,
      RevToggleKeyIcon,
      RingerIcon,
      RingerActiveIcon,
      RingerOffIcon,
      RingerRemoveIcon,
      SearchIcon,
      SettingsIcon,
      ShareIcon,
      SortIcon,
      SortDownIcon,
      SortLinesIcon,
      SortLinesAscendingIcon,
      SortUpIcon,
      StackIcon,
      StatusCircleCheckmarkIcon,
      StatusCircleErrorXIcon,
      SunnyIcon,
      SyncIcon,
      TVMonitorIcon,
      TableIcon,
      TagIcon,
      TagGroupIcon,
      TestBeakerIcon,
      TestBeakerSolidIcon,
      TranslateIcon,
      UndoIcon,
      UnlockIcon,
      UpIcon,
      UpdateRestoreIcon,
      UploadIcon,
      UserRemoveIcon,
      WaffleOffice365Icon,
      WarningIcon,
    ].map((Icon) => (
      <Center width={150} display="flex" flexDirection="column" my={2}>
        <Center size={48} mx={1} key={Icon.displayName}>
          <Icon color="primary" bg="white" size={24} />
        </Center>
        <Text textAlign="center" fontSize={12} color="text">
          {Icon.displayName}
        </Text>
      </Center>
    ))}
  </Box>
);

const Template = (args) => (
  <Box display="flex">
    <Center size={args.size || 30} mx={args.px || 1}>
      <HomeIcon color="error" bg="white" size={24} {...args} />
    </Center>
    <Center size={args.size || 30} mx={args.px || 1}>
      <AddIcon color="warning" bg="white" size={24} {...args} />
    </Center>
    <Center size={args.size || 30} mx={args.px || 1}>
      <SearchIcon color="info" bg="white" size={24} {...args} />
    </Center>
    <Center size={args.size || 30} mx={args.px || 1}>
      <MailIcon color="success" bg="white" size={24} {...args} />
    </Center>
  </Box>
);

export const Color = Template.bind({});
Color.args = {
  color: 'primary',
};

export const Size = Template.bind({});
Size.args = {
  size: 40,
};
