 app:
  name: app
  mode: test
  server:
    rest:
      port: 8080
    rpc:
      port: 8081
  logger:
    code: zerolog
    level: trace
    console: true
    static:
      app: true
      git: true
      host: true
  database:
    code: postgres
    dsn: "host=localhost port=5432 user=Robin password=test dbname=cx-tasks-test sslmode=disable"
  serializer:
    code: json
  contact:
    name: Robin Shi
    email: robinshi@outlook.com
