const defaultState = {
  projectFilters: {
    filterTerm: '',
  },
  recentProjects: {
    '1': {
      id: 1,
      title: 'Prototoye design for CxTasks',
      color: 'orange',
      my_issue_count: 1,
      owner: 'Bob',
      updated_at: '2021/2/18',
      due_date: '2021/2/28',
    },
    '2': {
      id: 2,
      title: 'Frontend dev for CxTasks',
      color: 'blue',
      my_issue_count: 2,
      owner: 'Bob',
      updated_at: '2021/2/20',
      due_date: '2021/2/26',
    },
    '3': {
      id: 3,
      title: 'Backend dev for CxTasks',
      color: 'pink',
      my_issue_count: 2,
      owner: 'Alice',
      updated_at: '2021/2/21',
      due_date: '2021/2/25',
    },
  },
  tasks: {
    '22': {
      id: 22,
      title: 'Redesign the kanban this week for review',
      description: 'Hi description',
      taskKind: 'Story',
      project: 'Frontend dev for CxTasks',
      status: 12,
      assignee: 'Alice',
      updated_at: '2021/2/3',
      assigned_at: '2021/2/3',
      due_date: '2021/2/20',
    },
    '21': {
      id: 21,
      title: 'Decide the design colors',
      description: '',
      taskKind: 'Task',
      project: 'Frontend dev for CxTasks',
      status: 12,
      assignee: 'Alice',
      updated_at: '2021/2/17',
      assigned_at: '2021/2/13',
      due_date: '2021/2/18',
    },
    '24': {
      id: 24,
      title:
        "Test the cover of the card, this is a long title test for the card and detail page, just have fun. That's really great.",
      description:
        "Hi description this is a long description for testing, just have fun for it. That'great really. hahahahah. good.",
      taskKind: 'Task',
      project: 'Backend dev for CxTasks',
      status: 13,
      assignee: 'Bob',
      updated_at: '2021/2/18',
      assigned_at: '2021/2/13',
      due_date: '2021/2/10',
    },
    '20': {
      id: 20,
      title: 'Implement the filter function',
      description: '',
      taskKind: 'Story',
      project: 'Frontend dev for CxTasks',
      status: 14,
      assignee: 'Bob',
      updated_at: '2021/2/3',
      assigned_at: '2021/2/3',
      due_date: '2021/2/5',
    },
  },
};
export default defaultState;
