export const projectSeed = {
  '1': {
    id: '1',
    title: 'CxTask Prototoye',
    description: 'description',
    color: 'orange',
    my_open_task: '0',
    owner: '1',
    updated_at: '2021/2/18',
    due_date: '2021/3/28',
  },
  '2': {
    id: '2',
    title: 'CxTask Frontend',
    description: 'description',
    color: 'blue',
    my_open_task: '0',
    owner: '1',
    updated_at: '2021/2/20',
    due_date: '2021/3/26',
  },
  '3': {
    id: '3',
    title: 'CxTask Backend',
    description: 'description',
    color: 'pink',
    my_open_task: '0',
    owner: '2',
    updated_at: '2021/2/21',
    due_date: '2021/3/25',
  },
};
